# Name of workflow
name: hello-user
# on – определяет события, которые запускают воркфлоу
on:
  - push
  - pull_request

jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v2
      # Step's name
      - name: Say "Hello, user!""
        # Echo "Hello, <user>!"
        run: |
          make say-hello
